apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../helm/mi-app   # ← ¡Esta es la ruta correcta!

helmCharts:
  - name: mi-app
    includeCRDs: true
    valuesFile: patch-values.yaml