apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mi-app-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/1103461933/mi-app-infra.git'  # Reemplaza con tu usuario
    targetRevision: main
    path: helm/mi-app
    helm:
      valueFiles:
        - values.yaml
        - values-dev.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true