# Configuración específica para DEV
replicaCount: 1

image:
  tag: dev-fa9e2c77cd5de1ceee5b9e4ddbc878af731cd10a

ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: dev.mi-app.com
      paths:
        - path: /
          pathType: Prefix

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi